=== yassirH9/LNDMonumentsAPI/Monuments.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.yassir.com"
    xmlns="https://www.yassir.com" elementFormDefault="qualified">
    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="row" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="N" minOccurs="1" maxOccurs="1" type="xs:integer"></xs:element>
                            <xs:element name="TITULO" minOccurs="1" maxOccurs="1" type="xs:string"></xs:element>
                            <xs:element name="AUTOR" minOccurs="1" maxOccurs="1" type="xs:string"></xs:element>
                            <xs:element name="URL" minOccurs="1" maxOccurs="1" type="xs:string"></xs:element>
                            <xs:element name="UBICACION" minOccurs="1" maxOccurs="1" type="xs:string"></xs:element>
                            <xs:element name="IMAGEN" minOccurs="1" maxOccurs="1" type="xs:string"></xs:element>
                            <xs:element name="FECHA" minOccurs="1" maxOccurs="1" type="xs:string"></xs:element>
                            <xs:element name="DISTRITO" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
                            <xs:element name="HORARIO" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="_id" type="xs:integer"/>
                    </xs:complexType>                   
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== yassirH9/LNDMonumentsAPI/Monuments.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="https://www.yassir.com" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://www.yassir.com Monuments.xsd"
>
    <row _id="1">
        <N>332</N>
        <TITULO>Las Cuatro Estaciones - El Invierno</TITULO>
        <AUTOR>Anónimo</AUTOR>
        <URL>http://esculturasdegrancanaria.blogia.com/2008/030203-escultura-las-cuatro-estaciones-el-verano.php</URL>
        <UBICACION>Zona limítrofe entre los barrios de Triana y Vegueta</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/332.JPG</IMAGEN>
        <FECHA>1815</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="2">
        <N>333</N>
        <TITULO>Las Cuatro Estaciones - El Otoño</TITULO>
        <AUTOR>Anónimo</AUTOR>
        <URL>http://fotografiasdeesculturas.blogspot.com.es/2011/01/esculturas-de-las-cuatro-estaciones.html</URL>
        <UBICACION>Zona limítrofe entre los barrios de Triana y Vegueta</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/333.JPG</IMAGEN>
        <FECHA>1815</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="3">
        <N>334</N>
        <TITULO>Las Cuatro Estaciones - El Verano</TITULO>
        <AUTOR>Anónimo</AUTOR>
        <URL>http://historiadegrancanaria.blogspot.com.es/2010/03/esculturas-de-1815.html</URL>
        <UBICACION>Zona limítrofe entre los barrios de Triana y Vegueta</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/334.JPG</IMAGEN>
        <FECHA>1815</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="4">
        <N>335</N>
        <TITULO>Las Cuatro Estaciones - La Primavera</TITULO>
        <AUTOR>Anónimo</AUTOR>
        <URL>http://esculturasbermaxo.blogspot.com.es/2013/11/escultura-las-cuatro-estaciones-en-las.html</URL>
        <UBICACION>Zona limítrofe entre los barrios de Triana y Vegueta</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/335.JPG</IMAGEN>
        <FECHA>1815 ( la original )</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="5">
        <N>339</N>
        <TITULO>Perros de la Plaza de Santa Ana  y Cabezas de León</TITULO>
        <AUTOR>Henri Alfred Jacquemart</AUTOR>
        <URL>http://www.laspalmasgc.es/views/La%20Ciudad/Historia/Cronista%20de%20la%20Ciudad/documentos/120203PerrosSantaAna.pdf</URL>
        <UBICACION>Plaza de Santa Ana / Cl. Obispo Codina</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/339.JPG</IMAGEN>
        <FECHA>Circa última década del siglo XIX</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="6">
        <N>340</N>
        <TITULO>Arte</TITULO>
        <AUTOR>Boutellier</AUTOR>
        <URL>http://www.urbelaspalmas.com/casas-consistoriales-para-caballeros-de-mesa-larga/</URL>
        <UBICACION>Plaza de Santa Ana</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/340.JPG</IMAGEN>
        <FECHA>1909</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="7">
        <N>341</N>
        <TITULO>Comercio</TITULO>
        <AUTOR>Boutellier</AUTOR>
        <URL>http://www.urbelaspalmas.com/casas-consistoriales-para-caballeros-de-mesa-larga/</URL>
        <UBICACION>Plaza de Santa Ana</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/341.JPG</IMAGEN>
        <FECHA>1909</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="8">
        <N>342</N>
        <TITULO>Navegación</TITULO>
        <AUTOR>Boutellier</AUTOR>
        <URL>http://www.urbelaspalmas.com/casas-consistoriales-para-caballeros-de-mesa-larga/</URL>
        <UBICACION>Plaza de Santa Ana</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/342.JPG</IMAGEN>
        <FECHA>1909</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="9">
        <N>343</N>
        <TITULO>Agricultura</TITULO>
        <AUTOR>Boutellier</AUTOR>
        <URL>http://www.urbelaspalmas.com/casas-consistoriales-para-caballeros-de-mesa-larga/</URL>
        <UBICACION>Plaza de Santa Ana</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/343.JPG</IMAGEN>
        <FECHA>1909</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="10">
        <N>355</N>
        <TITULO>Monumento a D. Diego Mesa de León</TITULO>
        <AUTOR>Plácido Fleitas Hernández</AUTOR>
        <URL>http://es.wikipedia.org/wiki/Pl%C3%A1cido_Fleitas</URL>
        <UBICACION>Plazoleta Diego Mesa de León</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/355.JPG</IMAGEN>
        <FECHA>1957</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="11">
        <N>357</N>
        <TITULO>Monumento a D. José Viera y Clavijo</TITULO>
        <AUTOR>Plácido Fleitas Hernández</AUTOR>
        <URL>http://es.wikipedia.org/wiki/Pl%C3%A1cido_Fleitas</URL>
        <UBICACION>Cl. Roque Morera</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/357.JPG</IMAGEN>
        <FECHA>1958</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="12">
        <N>358</N>
        <TITULO>Busto al General San Martín</TITULO>
        <AUTOR>Luis Perlotti</AUTOR>
        <URL>http://es.wikipedia.org/wiki/Luis_Perlotti</URL>
        <UBICACION>Cl.Tucumán</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/358.JPG</IMAGEN>
        <FECHA>C. 1961</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="13">
        <N>370</N>
        <TITULO>Monumento a San Francisco de Asís</TITULO>
        <AUTOR>Francisca Melián Chirino</AUTOR>
        <URL>http://www.diccionariodeartistas.org/index.php?option=com_content&amp;task=view&amp;id=507&amp;Itemid=615</URL>
        <UBICACION>Cl. Juan Sebastián Bach</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/370.JPG</IMAGEN>
        <FECHA>1981</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="14">
        <N>381</N>
        <TITULO>Monumento a Pepe Caña Dulce</TITULO>
        <AUTOR>Felipe Tomás Vega Domínguez. Escuela Taller de Agüimes</AUTOR>
        <URL>http://www.barriodesanjose.com/blog_barriodesanjose/?p=13777</URL>
        <UBICACION>Rotonda Pepe Caña Dulce, Paseo San José N 54</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/381.JPG</IMAGEN>
        <FECHA>1992</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="15">
        <N>383</N>
        <TITULO>Busto de Manolo Millares</TITULO>
        <AUTOR>M. Alonso Muñoz</AUTOR>
        <URL>http://www.march.es/arte/exposiciones/artista.asp?clave_autor=380&amp;clave_expo=39</URL>
        <UBICACION>Parque Manolo Millares</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/383.JPG</IMAGEN>
        <FECHA>1993</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="16">
        <N>401</N>
        <TITULO>Lady Harimaguada</TITULO>
        <AUTOR>Martín Chirino López</AUTOR>
        <URL>http://www.martinchirino.com/</URL>
        <UBICACION>Avenida Marítima</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/401.JPG</IMAGEN>
        <FECHA>1996</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="17">
        <N>410</N>
        <TITULO>Monumento a Juan Brito García</TITULO>
        <AUTOR>Anónimo</AUTOR>
        <URL>http://www.laestrellaquenosguia.com/index.php?option=com_content&amp;view=article&amp;id=177%3Aesculturas-las-palmas-3&amp;catid=1%3Alatest-news&amp;Itemid=162</URL>
        <UBICACION>Paseo de San José N 102</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/410.JPG</IMAGEN>
        <FECHA>1999</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="18">
        <N>450</N>
        <TITULO>Fuente de la Plaza de Santo Domingo</TITULO>
        <AUTOR>Anónimo</AUTOR>
        <URL />
        <UBICACION>Plaza de Santo Domingo</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/450.JPG</IMAGEN>
        <FECHA>1792</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="19">
        <N>451</N>
        <TITULO>Fuente Monumental del Espíritu Santo</TITULO>
        <AUTOR>Manuel Ponce de León y Falcón</AUTOR>
        <URL>http://www.racba.es/index.php/listado-alfabetico/157-ponce-de-leon-y-falcon-manuel</URL>
        <UBICACION>Plaza del Espíritu Santo</UBICACION>
        <IMAGEN>http://datosabiertos.laspalmasgc.es/repositorio/mobiliario/fotos_monumentos/451.JPG</IMAGEN>
        <FECHA>1862 a 1869</FECHA>
        <DISTRITO>DISTRITO VEGUETA, CONO SUR Y TAFIRA</DISTRITO>
    </row>
    <row _id="20">
